### ISSUE TITLE
Missing TiaC Magpie STM32F777NIHx

### ISSUE THREAD

**Issue by rexut** [tiacsys/bridle#3]
The Magpie board made by Three is a Company (TiaC) and based on STM32F777NIHx provide an affordable and flexible way for users to build prototypes and try out new concepts target communication systems.

**Status:**

1. configured (DTS/Kconfig):

   - [x] User LED 1/2
   - [x] UART 7 TX/RX/RTS/CTS
   - [x] ETH MII/MDIO
   - [x] USB OTG FS DM/DP (device)
   - [ ] USB OTG HS DM/DP (host/hub)
   - [x] CAN 1 TX/RX
   - [x] CAN 2 RX/TX
   - [x] I2C 2 SDA/SCL
   - [x] TiaC MAGPIE Pin Header
   - [x] TiaC MAGPIE Pin Header : USART 3 TX/RX
   - [x] TiaC MAGPIE Pin Header : UART 4 TX/RX
   - [x] TiaC MAGPIE Pin Header : UART 5 TX/RX
   - [x] TiaC MAGPIE Pin Header : UART 8 TX/RX/RTS/CTS
   - [x] TiaC MAGPIE Pin Header : I2C 3 SCL/SDA
   - [x] TiaC MAGPIE Pin Header : I2C 4 SCL/SDA
   - [x] TiaC MAGPIE Pin Header : SPI 4 MOSI/NSS/SCK/MISO
   - [x] TiaC MAGPIE Pin Header : SPI 5 MOSI/NSS/SCK/MISO
   - [x] TiaC MAGPIE Pin Header : PWM TIM 8 CH1/2/3/4
   - [x] TiaC MAGPIE Pin Header : ADC 3 IN9/IN14/IN15

2. manual tested:

   - [x] JTAG(SWD) TMS/TCK/TDI/TDO/TRST : ST-Link, OpenOCD
   - [x] UART 7 : Zephyr Shell Console
   - [x] ETH : DHCPv4 Client, Telnet Server, HTTP Web Server
   - [x] USB OTG FS (device) : USB Mass Storage (RAM/FATFS)
   - [ ] USB OTG HS (host/hub) : [Only USB device function is supported in Zephyr at the moment](https://github.com/zephyrproject-rtos/zephyr/issues/12386)
   - [ ] CAN 1 : t.b.d.
   - [ ] CAN 2 : [Simultaneous use of CAN_1 and CAN_2 not supported yet](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/can/can_stm32.c#L26)
   - [x] I2C 2 : Zephyr Shell Console (i2cdetect)
   - [ ] TiaC MAGPIE Pin Header (for Shields)
   - [ ] TiaC MAGPIE Pin Header : USART 3 : t.b.d.
   - [ ] TiaC MAGPIE Pin Header : UART 4 : t.b.d.
   - [ ] TiaC MAGPIE Pin Header : UART 5 : t.b.d.
   - [ ] TiaC MAGPIE Pin Header : UART 8 : t.b.d.
   - [ ] TiaC MAGPIE Pin Header : I2C 3 : Zephyr Shell Console (i2cdetect)
   - [ ] TiaC MAGPIE Pin Header : I2C 4 : Zephyr Shell Console (i2cdetect)
   - [x] TiaC MAGPIE Pin Header : SPI 4 : SPI Loopback
   - [x] TiaC MAGPIE Pin Header : SPI 5 : SPI Loopback
   - [ ] TiaC MAGPIE Pin Header : PWM TIM 8 : Zephyr Shell Console (pwm)
   - [x] TiaC MAGPIE Pin Header : ADC 3 : Zephyr Shell Console (adc)

3. automated test:
 
   - [x] [Zephyr : kernel](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/os/kernel.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [x] [ARM : IRQ, NMI, TZ Wrap, Thread Swap, System Call / SW Vector](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/arch/arm.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [x] ARM Cortex-M7 : [MPU and Stack Protection](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/arch/arm.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [x] ARM Cortex-M7 : [RTC on LSE](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/counter.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [x] ARM Cortex-M7 : [IWDG as Watchdog](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/watchdog.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [ ] ARM Cortex-M7 : [WWDG as Watchdog](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/watchdog.html) ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)
   - [x] ARM Cortex-M7 : [RNG for Entropy](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/entropy.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [ ] ARM Cortex-M7 : CRC for Hash (Zephyr has not yet any framework to access HW accelerated CRC/HASH units) ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)
   - [x] [Hardware Info-API](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/hwinfo.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [x] [User LED 1/2](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/gpio.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [ ] UART 7
   - [ ] ETH
   - [ ] USB OTG FS (device)
   - [ ] USB OTG HS (host/hub)
   - [ ] CAN 1
   - [ ] CAN 2
   - [ ] I2C 2
   - [x] TiaC MAGPIE Pin Header : [USART 3 & 4](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/uart.html) **(not yet)** ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)
   - [x] TiaC MAGPIE Pin Header : [I2C 4 & 3](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/i2c.html) **(FAIL)** ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+)
   - [x] TiaC MAGPIE Pin Header : [SPI 4](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/spi.html) ![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+)
   - [x] TiaC MAGPIE Pin Header : [PWM TIM 8](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/pwm.html) **(FAIL)** ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+)
   - [x] TiaC MAGPIE Pin Header : [ADC 3](https://lipro-zephyr.github.io/lpn-bridle/lpnb/boards/arm/tiac_magpie/doc/tests/drivers/adc.html) **(not yet)** ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)
